version: "3.3"
services:
  db:
    image: "mariadb:10.1"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: flask_db
  web:
    image: webapp:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    # deploy: 
    #   replicas: 3
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    # networks:
    #   - webnet
  
# networks:
#   webnet:

volumes:
  db-vol: